# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# SPDX-License-Identifier: BSD-3-Clause

from isaaclab.managers import ObservationTermCfg as ObsTerm
from isaaclab.utils import configclass

from .franka_end_effector_tracking_delayed_multi_frequency_env_cfg import (
    FrankaEndEffectorTrackingDelayedMultiFrequencyEnvCfg,
)
from .franka_end_effector_tracking_env_cfg import figure_eight_target_acceleration


@configclass
class FrankaEndEffectorTrackingDelayedMultiFrequencyWithAccelerationEnvCfg(
    FrankaEndEffectorTrackingDelayedMultiFrequencyEnvCfg
):
    """Delayed multi-frequency tracking task that also exposes desired target acceleration."""

    def __post_init__(self):
        super().__post_init__()

        # Position, velocity, and acceleration are all commanded quantities generated by us.
        # Exposing acceleration gives the policy a local description of how the target is about to turn
        # without revealing figure-eight phase or tying the policy to one memorized trajectory.
        self.observations.policy.target_acceleration = ObsTerm(
            func=figure_eight_target_acceleration,
            params={"command_name": "ee_pose"},
        )
